# Generated by Django 4.0 on 2025-07-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responders',
            new_name='Responder',
        ),
    ]
