# Generated by Django 4.0 on 2025-07-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_order_product_order_responder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
