# Generated by Django 4.2.23 on 2025-07-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_order_cost_alter_inventory_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
