# Generated by Django 5.1.3 on 2025-08-01 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_order_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='updatedInventory',
            fields=[
                ('update_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.inventory')),
                ('responder', models.ManyToManyField(to='manager.responder')),
            ],
        ),
    ]
