# Generated by Django 5.1.3 on 2025-08-01 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_updatedinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedinventory',
            name='QuantityUsed',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
