# Generated by Django 4.2.23 on 2025-07-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_responder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="responder",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
