# Generated by Django 5.1.3 on 2025-08-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_updatedinventory_quantityused'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedinventory',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
