# Generated by Django 4.2.23 on 2025-07-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0008_responder_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responder",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profilePicture/defaultProfilePicture.jpg",
                null=True,
                upload_to="",
            ),
        ),
    ]
