# Generated by Django 4.2.23 on 2025-07-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_alter_responder_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responder",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="defaultProfilePicture.jpg", null=True, upload_to=""
            ),
        ),
    ]
