# Generated by Django 4.2.23 on 2025-07-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0010_alter_responder_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="supplier",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
