# Generated by Django 4.2.23 on 2025-07-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0011_alter_order_supplier"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="note",),
        migrations.RemoveField(model_name="order", name="responder",),
    ]
