# Generated by Django 4.2.23 on 2025-07-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0012_remove_order_note_remove_order_responder"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
