# Generated by Django 4.2.23 on 2025-07-29 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0013_order_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="responder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manager.responder",
            ),
        ),
    ]
