# Generated by Django 4.2.23 on 2025-08-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0014_order_responder"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
