# Generated by Django 4.2.23 on 2025-08-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0015_order_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="responder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manager.responder",
                to_field="user",
            ),
        ),
    ]
