# Generated by Django 4.2.23 on 2025-08-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0017_alter_order_product_alter_order_responder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="responder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.responder",
                to_field="user",
            ),
        ),
    ]
