# Generated by Django 4.2.23 on 2025-08-01 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manager", "0018_alter_order_product_alter_order_responder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responder",
            name="name",
            field=models.CharField(default="No Name User", max_length=200),
        ),
    ]
