# Generated by Django 4.2.23 on 2025-08-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0019_alter_responder_name_alter_responder_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responder",
            name="name",
            field=models.CharField(default="No Name User", max_length=200, null=True),
        ),
    ]
