# Generated by Django 4.2.23 on 2025-08-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0020_alter_responder_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responder",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
