# Generated by Django 4.2.23 on 2025-08-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_updatedinventory_notes"),
        ("manager", "0022_alter_responder_user"),
    ]

    operations = []
