# Generated by Django 4.2.23 on 2025-08-04 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0023_merge_20250804_2232"),
    ]

    operations = [
        migrations.RemoveField(model_name="updatedinventory", name="responder",),
        migrations.AddField(
            model_name="updatedinventory",
            name="responder",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.responder",
            ),
        ),
    ]
