# Generated by Django 4.2.23 on 2025-08-04 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0024_remove_updatedinventory_responder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="updatedinventory",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.inventory",
            ),
        ),
    ]
