# Generated by Django 4.2.23 on 2025-08-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0025_alter_updatedinventory_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="ideal_quantity",
            field=models.IntegerField(null=True),
        ),
    ]
