# Generated by Django 5.2.4 on 2025-08-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_alter_updatedinventory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedinventory',
            name='packNum',
            field=models.IntegerField(null=True),
        ),
    ]
