# Generated by Django 5.2.4 on 2025-08-06 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_updatedinventory_packnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatedinventory',
            old_name='QuantityUsed',
            new_name='quantityUsed',
        ),
    ]
