# Generated by Django 5.2.4 on 2025-08-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_rename_quantityused_updatedinventory_quantityused'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='itemType',
            field=models.CharField(choices=[('Miscellaneous', 'Miscellaneous'), ('OPA', 'OPA'), ('MSK', 'MSK'), ('Oxygen', 'Oxygen'), ('Gauze', 'Gauze'), ('PPE', 'PPE')], null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='optimalStock',
            field=models.IntegerField(null=True),
        ),
    ]
