# Generated by Django 5.2.4 on 2025-08-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_inventory_itemtype_inventory_optimalstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='optimalStock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
